# Generated by Django 4.2.3 on 2023-08-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("slug", models.CharField(max_length=100, verbose_name="Slug")),
                ("content", models.TextField(verbose_name="Содержание")),
                (
                    "preview",
                    models.ImageField(
                        blank=True, upload_to="blog", verbose_name="Превью"
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=True, verbose_name="Признак публикации"
                    ),
                ),
                (
                    "views_count",
                    models.IntegerField(default=0, verbose_name="Просмотры"),
                ),
            ],
            options={
                "verbose_name": "Запись блога",
                "verbose_name_plural": "Записи блога",
                "ordering": ["-created_at"],
            },
        ),
    ]
